name: CI

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release Drafter
      uses: release-drafter/release-drafter@v6.0.0
      with: 
        commitish: ref/heads/main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}