name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release Drafter
      uses: release-drafter/release-drafter@v6.0.0
      with: 
        commitish: ref/heads/main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}